---
title: "Data Import"
output: github_document
---

```{r, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```


## Data Import CSVs

Let's import data using the readr package

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
litters_df
```

Look at the data
```{r}
head(litters_df)
tail(litters_df)
```


```{r, eval=FALSE}
view(litters_df)
```

```{r}
skimr::skim(litters_df)
```


read.csv options...
```{r}
read_csv("data/FAS_litters.csv", na = "NA", skip=0)

litters_data = read_csv(file = "data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```


## Other file formats

Excel spreadsheet
```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

```{r, eval=FALSE}
view(mlb_df)
```


```{r}
lotr_words_df = read_excel("data/LotR_Words.xlsx",
                        range = "B3:D6")
```

## Still more formats...

Read in a SAS dataset.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
pulse_df
```


## Data export
```{r}
write_csv(lotr_words_df, file = "data/lotr_words_df.csv")
```


## Why not base R?

```{r}
dont_do_this_df = read.csv("data/FAS_litters.csv")
```


